---
deployment:
  tasks:
    - export DEPLOYPATH=/home4/gilpilco/public_html/assets/
    - export DEPLOYPATH_ASSETS=/home4/gilpilco/public_html/assets/
    - /bin/cp dist/gilpilweb/* $DEPLOYPATH
    - /bin/cp dist/gilpilweb/* $DEPLOYPATH_ASSETS